CReview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('reviews.urls',namespace = "reviews")),
    path('admin/', admin.site.urls),
]

reviews/urls.py
from django.urls import path, include
from . import views
from random import randint, choice


app_name = 'reviews'
urlpatterns = [
    path('',views.index_view,name='index_view'),
    path('dept/<str:dept_id>', views.mat_list, name='mat_list'),
    path('mat/<str:mat_id>', views.course_list, name='course_list'),
    path('mat/<str:mat_id>/<str:course_id>', views.course_detail, name = 'course_detail'),
    path('mat/<str:mat_id>/<str:course_id>/add_recom',views.add_recom, name = 'add_recom'),
    path('contacto/',views.contacto,name='contacto'),
    path('msg_send/',views.send_msg,name='sent'),
    path('delete_rev/<str:rev_id>/',views.del_rev,name='del_rev'),
    path('flag_rev/<str:rev_id>',views.flag_rev,name='flag_rev'),
    path('search/',views.search,name='search')
]

reviews/models.py
from django.db import models
import numpy as np
import datetime


class Dept(models.Model):
    name = models.CharField(max_length = 150)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Mat(models.Model):
    name = models.CharField(max_length = 150)
    dep = models.ForeignKey(Dept, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length = 100)
    mat = models.ForeignKey(Mat, on_delete=models.CASCADE)

    def average_recs(self):
        try:
            total = 0
            upp = 0
            for i in self.coursereview_set.all():
                total += 1
                upp += i.recom
            avg = upp/total
            return avg*100
        except:
            return -1

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


class CourseReview(models.Model):
    RECOM_CHOICES = (
        (1, 'SI'),
        (0, 'NO'),
    )

    CUATR_CHOICES = (
        (1, '1C'),
        (2, '2C'),
    )

    YEAR_CHOICES = ((r,r) for r in range(2010, datetime.date.today().year+1))

    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 1000)
    year = models.IntegerField(('year'), choices = YEAR_CHOICES, default=datetime.datetime.now().year)
    cuatr = models.IntegerField(choices = CUATR_CHOICES)
    recom = models.IntegerField(choices = RECOM_CHOICES)
    flag = models.IntegerField(default = 0)



class AdminMessage(models.Model):
    mensaje = models.CharField(max_length=1000)
    date = models.DateTimeField('date published')

reviews/forms.py
from django.forms import ModelForm, Textarea
from reviews.models import CourseReview, AdminMessage


class RecomForm(ModelForm):
    class Meta:
        model = CourseReview
        fields = ['year','cuatr','recom','comment']
        widgets = {
            'comment': Textarea(attrs={'cols': 40, 'rows': 10}),
        }


class MessageForm(ModelForm):
    class Meta:
        model = AdminMessage
        fields = ['mensaje']
        widgets={
            'mensaje': Textarea(attrs={'cols':40,'rows':10}),
        }

reviews/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Dept, Mat, Course, CourseReview, AdminMessage
from .forms import RecomForm, MessageForm
from django.contrib.admin.views.decorators import staff_member_required
from django.template.loader import render_to_string
from django.http import JsonResponse
import datetime


def dept(request):
    depts = Dept.objects.order_by('name')
    context = {'dept_list':depts}
    return (context)


def mat_list(request, dept_id):
    mats_no = Mat.objects.filter(dep = dept_id)
    mats = mats_no.order_by('id')
    depto = Dept.objects.get(id = dept_id)
    return render(request,'reviews/mat_list.html',{'mat_list':mats,'depto':depto})


def search(request):
    ctx = {}
    url_parameter = request.GET.get("q")
    if url_parameter and len(url_parameter) > 2:
        cate = Course.objects.filter(name__icontains=url_parameter)
    else:
        cate = []

    ctx["cate"] = cate

    if request.is_ajax():
        html = render_to_string(template_name="reviews/partial-res.html", context={"cate": cate})
        data_dict = {"html_from_view": html}
        return JsonResponse(data=data_dict, safe=False)

    return render(request, "reviews/index.html", context=ctx)


def index_view(request):
    val1=search(request)
    val2=dept(request)
    ctx={'v1':val1,'v2':val2}
    return render(request,"reviews/index.html",context = ctx)


def course_list(request, mat_id):
    courses_no = Course.objects.filter(mat = mat_id)
    courses = courses_no.order_by('name')
    materia = Mat.objects.get(id = mat_id)
    context = {'course_list':courses, 'materia':materia}
    return render(request,'reviews/course_list.html',context)


def course_detail(request, mat_id, course_id):
    course_no = get_object_or_404(Course, pk=course_id)
    course_rev = CourseReview.objects.filter(course=course_id).order_by('-year','-cuatr')
    pagin = Paginator(course_rev,5)
    form = RecomForm()
    page_number = request.GET.get('page')
    try:
        revs = pagin.page(page_number)
    except PageNotAnInteger:
        revs = pagin.page(1)
    except EmptyPage:
        revs = pagin.page(pagin.num_pages)


    return render(request, 'reviews/course_detail.html', {'course': course_no, 'form': form, 'listado':revs})



def add_recom(request, course_id, mat_id):
    course = get_object_or_404(Course, pk=course_id)
    mat = get_object_or_404(Mat, pk=course.mat.id)
    form = RecomForm(request.POST)
    if form.is_valid():
        recom = form.cleaned_data['recom']
        comment = form.cleaned_data['comment']
        cuatr = form.cleaned_data['cuatr']
        year = form.cleaned_data['year']
        CReview = CourseReview()
        CReview.course = course
        CReview.recom = recom
        CReview.cuatr = cuatr
        CReview.year = year
        CReview.comment = comment
        CReview.save()
        return HttpResponseRedirect(reverse('reviews:course_detail',args=(mat.id,course.id,)))

    return render(request, 'reviews/course_detail.html', {'course':course, 'form':form})



def flag_rev(request,rev_id):
    r = CourseReview.objects.filter(id=rev_id).update(flag = -1)
    print("flagging rev:"+rev_id)
    return HttpResponse(status=204)



def del_rev(request, rev_id):
    # TODO: SQL delete
    print(type(rev_id))
    print("deleting"+rev_id)
    return HttpResponse(status=204)



def contacto(request):
    form = MessageForm()
    return render(request,'reviews/contacto.html',{'form':form})



def send_msg(request):
    form = MessageForm(request.POST)
    if form.is_valid():
        mensaje = form.cleaned_data['mensaje']
        sendM = AdminMessage()
        sendM.mensaje = mensaje
        sendM.date = datetime.datetime.now()
        sendM.save()
        return HttpResponseRedirect(reverse('reviews:contacto'))
    return render(request, 'reviews/contacto.html',{'form':form})

reviews/templates/reviews/base.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/tbase.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <title>Fub REVIEWS</title>
        <style>
            .bg-1 {
                background-color: #B9E0F7;
                color: #ffffff;
            }
        </style>
    </head>



    <body>
        <div class = 'container-fluid bg-1'>
            <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
              <div class="container">
                <a class="navbar-brand" href="{% url 'reviews:index_view'%}"><strong>FIR</strong></a>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="navbar-brand" href="{% url 'reviews:index_view'%}"><strong>HOME</strong></a>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>


            <div class="row justify-content-center">
                <div class="col-12 q">
                    <h1 class="mt-2">{% block title %}
                        {% endblock %}</h1>
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <footer class="text-center">
          <p>Agregar Materia o Curso<br> <a href="{% url 'reviews:contacto' %}"> Contacto</a></p>
          <p>Made By <br><a href="#" data-toggle="tooltip" title="Visit #">J.J</a></p>

          <script type="text/javascript" src="{% static "scripts/main.js" %}"></script>

        </footer>
    </body>
</html>

reviews/templates/reviews/base01.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/tbase.css' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
        <title>Fub REVIEWS</title>
    </head>

    <body>
        <div class="container1 bg-0">
        <header>
          <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar">
            <div class="container">
              <a class="navbar-brand" href="{% url 'reviews:index_view'%}"><strong>FIR</strong></a>
              <div class="collapse navbar-collapse" id="navbarSupportedContent-7">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="navbar-brand" href="{% url 'reviews:index_view'%}"><strong>HOME</strong></a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          <div class="view" style="background-image: url({% static 'FI.jpg' %}); background-repeat: no-repeat; background-size: cover; background-position: center center;">
            <div class="mask rgba-black-light align-items-center">
              <div class="container">
                <div class="row21">
                  <div class="col22 mb-4 white-text">
                    <br>
                    <h1 class="h1 white-text text-uppercase font-weight-bold mb-0 pt-md-5 pt-5"><strong>ULTRA REVIEWS</strong></h1>
                    <hr class="hr-light my-4">
                    {% block search %}
                    {% endblock %}
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
        </header>
        <main>
            <div class = 'container-fluid bg-1'>
            <div class="row justify-content-center">
              <div class="col-12 a">
                  <h1 class="mt-2">{% block title %}{% endblock %}</h1>
                  {% block content %}
                  {% endblock %}
              </div>
            </div>
        </div>
        </main>
        <footer class="text-center">
          <p>Agregar Materia o Curso<br> <a href="{% url 'reviews:contacto' %}"> Contacto</a></p>
          <p>Made By <br><a href="#" data-toggle="tooltip" title="Visit #">J.J</a></p>
          <script type="text/javascript" src="{% static "scripts/main.js" %}"></script>
        </footer>
    </body>
</html>
</html>

reviews/templates/reviews/contacto.html
{% extends 'reviews/base.html' %}
{% load crispy_forms_tags %}


{% block title %}
<h2>Enviar Mensaje</h2>
<hr class="mt-0 mb-4">
{% endblock %}


{% block content %}
<div class="card3 text-center text-white bg-dark mb-2">
    <div class="card-body">
        <h3>Add your review</h3>
        <form action="{% url 'reviews:sent'%}" method="post">
        {% csrf_token %}
            {{form.mensaje|as_crispy_field}}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
</div>
{% endblock %}

reviews/templates/reviews/course_detail.html
{% extends 'reviews/base.html' %}

{% load crispy_forms_tags %}


{% block title %}

<div class="card9 text-center text-white bg-dark mb-2">

    <h1 class="card-title">{{ course.name }}</h1>
    <hr>
    <div class="card-body">
        <h3 class="card-text"> {{course.mat.id}} - {{course.mat}}</h3>
    </div>
    <hr>
    {% if course.average_recs != -1%}
        <div class="card-body">
            <h5 class="card-text">{{ course.coursereview_set.count }} reviews (el {{ course.average_recs | floatformat }}% lo recomienda)</h5>
        </div>
        {% else %}
        <div class="card-body">
            <p class="card-text">No hay reviews</p>
        </div>
    {% endif %}

</div>

{% endblock %}

{% block content %}

{% if course.coursereview_set.all %}
    {% for review in listado %}
    <div class="card2 text-center text-white bg-dark mb-2" style="width: 21 rem;">
        <div class="card-body">

        {% if review.recom == 1 %}
                <h5 class="card-title"><strong>LO RECOMIENDO</strong></h5>
        {% else %}
                <h5 class="card-title"><strong>NO LO RECOMIENDO</strong></h5>
        {% endif %}

        <h6>cursada en el {{review.cuatr}} cuatrimestre de {{review.year}}</h6>
        <hr>
        <p class="card-text">{{ review.comment }}</p>
        <hr>
        <div class="text-right">

        {% if review.flag == 1 %}
            <a class="btn btn-dark btn-sm disabled" > Approved! </a>
        {% elif review.flag == -1 %}
            <a class="btn btn-dark btn-sm disabled"> Flagged! </a>
        {% else %}
            <a id="{{review.id}}" href="{% url 'reviews:flag_rev' review.id %}"  class="btn btn-dark btn-sm" onclick="flagButton(id)">Flag Review</a>
        {% endif %}

        {% if user.is_superuser %}
            <a id="{{review.id}}del" href="{% url 'reviews:del_rev' review.id%}" class ="btn btn-danger btn-sm" onclick="deleteButton(id)">DELETE REVIEW</a>
        {%endif%}
        </div>
        </div>
    </div>
    {% endfor %}

    {% if listado.has_other_pages %}
    <div class="card4 text-center text-white bg-dark mb-2">
    <div class="card-body">
    <div class="card-text">
    <ul class="pagination">
    {% if listado.has_previous %}
      <li><a href="?page={{ listado.previous_page_number }}" class ="btn btn-primary stretched-link">&laquo;</a></li>
    {% else %}
      <li class="disabled btn btn-primary"><span>&laquo;</span></li>
    {% endif %}
    {% for i in listado.paginator.page_range %}
      {% if listado.number == i %}
        <li class="active btn btn-primary"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}" class ="btn btn-primary stretched-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if listado.has_next %}
      <li><a href="?page={{ listado.next_page_number }}" class ="btn btn-primary stretched-link">&raquo;</a></li>
    {% else %}
      <li class="disabled btn btn-primary"><span>&raquo;</span></li>
    {% endif %}
    </ul>
    </div>
    </div>
    </div>
    {% endif %}
{% else %}
<div class="card3 text-center text-dark bg-warning mb-2">
    <div class="card-body">
        <p class="card-text">Be the first to write a review</p>
    </div>
</div>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div class="card card-1 text-center text-dark bg-warning mb-2">
    <div class="card-body">
        <h5 class="card-title">DEMO</h5>
        <p class="card-text">Los comentarios seran reemplazados por un placeholder</p>
    </div>
</div>
<div class="card3 text-center text-white bg-dark mb-2">
    <div class="card-body">
        <h3>Add your review</h3>
        <form action="{% url 'reviews:add_recom' course.mat course.id %}" method="post">
        {% csrf_token %}
            <div class='row'>
                <div class = 'col-4'>
                    {{form.year|as_crispy_field}}
                </div>
                <div class="col-4">
                    {{form.cuatr|as_crispy_field}}
                </div>
                <div class="col-4">
                    {{form.recom|as_crispy_field}}
                </div>
            </div>
            {{form.comment|as_crispy_field}}
            <button type="submit" class="btn btn-success">Save</button>
        </form>
    </div>
</div>

<script>
function flagButton(Id) {
    document.getElementById(Id).classList = "btn btn-dark btn-sm";
    document.getElementById(Id).classList.add('disabled');
    document.getElementById(Id).innerHTML = "Flagged!";
}
function deleteButton(Id){
    document.getElementById(Id).classList = "btn btn-danger btn-sm";
    document.getElementById(Id).classList.add('disabled');
    document.getElementById(Id).innerHTML = "Deleted!";
}
</script>
{% endblock %}

reviews/templates/reviews/course_list.html
{% extends 'reviews/base.html' %}



{% block title %}
<h2>Lista de Cursos de {{materia}}</h2>
<hr class="mt-0 mb-4">
{% endblock %}


{% block content %}
{% if course_list %}
<div class="row">
    {% for course in course_list %}
    <div class="col-sm-4">
        <div class="card text-center text-white bg-dark mb-2" style="width: 21 rem; height: 20 rem;">
            <div class="card-body">
                <h5 class="card-title">{{course.mat.id}}</h5>
                <hr>
                <p class="card-text">{{course.name}}</p>
                <a href="{% url 'reviews:course_detail' course.mat course.id %}" class="btn btn-primary stretched-link">Ver Cursos</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="row">
    <div class="col-12">
        <div class="card card5 text-center text-dark bg-warning mb-2" style="width: 21 rem; height: 40 rem;">
            <div class="card-body">
                <h5 class="card-title">OPS..</h5>
                <hr>
                <p class="card-text">No hay cursos para el Departamento elegido</p>
                <p class="card-text"><a href="{% url 'reviews:contacto' %}"> AGREGA UN CURSO</a> </p>
                <p class="card-text"><a href="{% url 'reviews:index_view'%}"> VOLVER AL INICIO</a></p>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

reviews/templates/reviews/depts_list.html
{% extends 'reviews/base01.html' %}
{% load bootstrap4 %}


{% block title %}
    <h2 class="text-center">Lista de Departamentos</h2>
    <hr class="mt-0 mb-4">
{% endblock %}


{% block content %}
{% if dept_list %}
<div class="row">
    {% for dept in dept_list %}
    <div class="col-sm-4">
        <div class="card card-1 text-center text-white bg-dark mb-2">
            <div class="card-body">
                <h5 class="card-title">{{dept.name}}</h5>
                <hr>
                <a href="{% url 'reviews:mat_list' dept.id %}" class="btn btn-primary stretched-link">Ver Materias</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No Hay Departamentos</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/index.html
{% extends "reviews/base01.html" %}

{% block title %}
    <h2 class="text-center">Lista de Departamentos</h2>
    <hr class="mt-0 mb-4">
{% endblock %}


{% block search %}
    <div class="input-group mb-3">
        <input id="user-input"type="text" class="form-control" placeholder="Busca por Curso!!">
    </div>
    <div id="replaceable-content">
        {% include 'reviews/partial-res.html' %}
    </div>
{% endblock %}


{% block content %}
{% if v2.dept_list %}
<div class="row">
    {% for dept in v2.dept_list %}
    <div class="col-sm-4">
        <div class="card card-1 text-center text-white bg-dark mb-2">
            <div class="card-body">
                <h5 class="card-title">{{dept.name}}</h5>
                <hr>
                <a href="{% url 'reviews:mat_list' dept.id %}" class="btn btn-primary stretched-link">Ver Materias</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No Hay Departamentos</p>
{% endif %}
{% endblock %}

reviews/templates/reviews/mat_list.html
{% extends 'reviews/base.html' %}


{% block title %}
<h2>Lista de Materias de {{depto}}</h2>
<hr class="mt-0 mb-4">
{% endblock %}


{% block content %}
{% if mat_list %}
<div class="row">
    {% for mater in mat_list %}
    <div class="col-sm-4 columna">
        <div class="card text-center text-white bg-dark mb-2">
            <div class="card-body">
                <h5 class="card-title">{{mater.id}}</h5>
                <hr>
                <p class="card-text">{{mater.name}}</p>
                <a href="{% url 'reviews:course_list' mater.id %}" class="btn btn-primary stretched-link">Ver Cursos</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
<div class="row">
    <div class="col-12">
        <div class="card text-center text-black bg-warning mb-2" style="width: 21 rem; height: 20 rem;">
            <div class="card-body">
                <h5 class="card-title">no hay materias para el Departamento elegido <br> <a href="{% url 'reviews:index_view'%}"> VOLVER AL INICIO</a></h5>
            </div>
        </div>
    </div>
</div>
    <!-- <p>No mater are available.</p> -->
{% endif %}
{% endblock %}

reviews/templates/reviews/partial-res.html
{% if cate %}
    <div class="list-group">
        {% for cur in cate %}
        <a href="{% url 'reviews:course_detail' cur.mat cur.id %}" class="list-group-item list-group-item-action list-group-item-info">{{cur.name}} - {{cur.mat}} - {{cur.mat.id}}</a>
        {% endfor %}
    </div>

{% endif %}